apiVersion: apps/v1
kind: Deployment
metadata:
  name: bz-f8t-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bz-f8t-admin
  template:
    metadata:
      labels:
        app: bz-f8t-admin
    spec:
      containers:
      - name: bz-f8t-admin
        image: $REGISTRY_LOGIN_SERVER/bz-f8t-admin:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__Postgres
          value: "$DB_ADMIN_CONNSTR"
        - name: ConnectionStrings__AzureServiceBus
          value: "$SERVICE_BUS_CONNSTR"
        - name: ConnectionStrings__ApplicationInsights
          value: "$APP_INSIGHTS_CONNSTR"
        resources:
          requests:
            cpu: 1m
            memory: 75Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - bz-f8t-admin
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bz-f8t-admin-hpa
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bz-f8t-admin
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: bz-f8t-admin-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: bz-f8t-admin