name: Build a docker image, push to the container registry and deploy into k8s

on:
  workflow_dispatch: {}
  push:
    paths-ignore:
    - 'src/Shared/**'
    - 'README.ME'
    - 'doc/**'
    - 'test/**'

jobs:
  build-and-deploy-service-in-dev:
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      ENVIRONMENT_TYPE: dev
      PROJECT_NAME: f8t
      SERVICE_NAME: admin
      AZURE_REGION_SHORT_NAME: ${{ vars.AZURE_REGION_SHORT_NAME }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
