name: Build & deploy service in uat/prod

on:
  push:
    tags:
      - 'v*'

jobs:
  build-service-in-uat:
    uses: ./.github/workflows/.script-build-service-docker-image-and-push-into-acr.yml
    with:
      ENVIRONMENT_TYPE: uat
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy-service-in-uat:
    uses: ./.github/workflows/.script-deploy-service-into-aks.yml
    needs: build-service-in-uat
    with:
      ENVIRONMENT_TYPE: uat
      AZURE_REGION_SHORT_NAME: ${{ vars.AZURE_REGION_SHORT_NAME }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy-service-in-prod:
    uses: ./.github/workflows/.script-deploy-service-into-aks.yml
    needs: 
    - deploy-service-in-uat
    with:
      ENVIRONMENT_TYPE: prod
      AZURE_REGION_SHORT_NAME: ${{ vars.AZURE_REGION_SHORT_NAME }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
